spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/luxury_car_db
    username: raghavjha
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8085

logging:
  level:
    root: INFO
    com.rtt.luxurycar: DEBUG
